version: '3.0'

services:
  python-docker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'

  redis:
    image: redis
    
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config.txt:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6739'
