name: Python and Docker CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint Python code
      run: pylint .  # Замените на вашу команду для запуска линтера

  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .  # Замените на вашу команду для сборки Docker-образа

  dependabot:
    name: Configure Dependabot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Dependabot configuration file
      run: |
        echo "version: 2" > dependabot.yml
        echo "updates:" >> dependabot.yml
        echo "  - package-ecosystem: 'pip'" >> dependabot.yml
        echo "    directory: '/'" >> dependabot.yml
        echo "    schedule:" >> dependabot.yml
        echo "      interval: 'daily'" >> dependabot.yml
        echo "    open-pull-requests-limit: 5" >> dependabot.yml
